web:
  bind: '0.0.0.0'
  port: 8080
  server: thin
db:
  uri: 'mongodb://127.0.0.1:27017/test'
instance:
  name: 'Alpha Centauri'
search:
  matchType: 'regex' #'regex' or 'equals'
hacks:
  preload_new_personnel: 'true' #'true' or 'false'
  show_explain: 'true' #'true' or 'false'